services:
  citilink_feed_handler:
    environment:
      - TZ=Europe/Moscow
    image: imediadev/citilink_feed_handler
    user: "1002:1002"
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - ./${FEEDS_FOLDER}:/app/${FEEDS_FOLDER}
      - /home/main_ftp_user/projects/citilink/${NEW_FEEDS_FOLDER}:/app/${NEW_FEEDS_FOLDER}
      - /home/main_ftp_user/projects/citilink/${JOIN_FEEDS_FOLDER}:/app/${JOIN_FEEDS_FOLDER}
